version: "3.7"

services:
  web:
    build: ./mx3s
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mx3s/:/usr/src/mx3s/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mat
      - POSTGRES_PASSWORD=mat
      - POSTGRES_DB=mx3s_db

volumes:
  postgres_data:
