# Generated by Django 3.1.7 on 2021-02-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20210228_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='time ended'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='time started'),
        ),
    ]
