# Generated by Django 3.1.7 on 2021-02-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('server', '0005_auto_20210228_1313')]

    operations = [
        migrations.RemoveField(model_name='simulation', name='current_gpu'),
        migrations.AlterField(
            model_name='gpu',
            name='current_simulation',
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='server.simulation',
            ),
        ),
    ]
