# Generated by Django 3.1.7 on 2021-03-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('server', '0006_auto_20210228_1520')]

    operations = [
        migrations.RenameField(model_name='simulation',
                               old_name='finished',
                               new_name='is_finished'),
        migrations.RemoveField(model_name='simulation', name='duration'),
        migrations.RemoveField(model_name='simulation', name='queued'),
        migrations.RemoveField(model_name='simulation', name='running'),
        migrations.AddField(
            model_name='simulation',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='is_queued',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='name',
            field=models.CharField(default='simulation name', max_length=200),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='start_time',
            field=models.DateTimeField(blank=True,
                                       default=None,
                                       null=True,
                                       verbose_name='Time Started'),
        ),
    ]
