# Generated by Django 3.1.7 on 2021-03-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='script',
            field=models.FileField(null=True, upload_to='', verbose_name='/tmp'),
        ),
    ]
