# Generated by Django 3.1.7 on 2021-03-01 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [('server', '0011_auto_20210301_1635')]

    operations = [
        migrations.DeleteModel(name='Document'),
        migrations.AddField(
            model_name='simulation',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='script',
            field=models.FileField(null=True, upload_to='', verbose_name='/'),
        ),
    ]
