# Generated by Django 3.1.7 on 2021-03-02 18:03

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20210301_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='simulation',
            name='script',
            field=models.FileField(null=True, upload_to=server.models.rename_script),
        ),
    ]
