# Generated by Django 3.1.7 on 2021-03-13 18:01

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20210302_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='simulation',
            name='script',
            field=models.FileField(null=True, upload_to=server.models.rename_script, validators=[server.models.file_upload_validator]),
        ),
    ]
